// packages/runtime/vue-runtime/src/plugins/runtime-plugin-vue-renderer/controller-renderer.vue
<script setup lang="ts">
import type { DefaultController } from '@p-lc/runtime'
import type { VueRendererProps } from '../runtime-plugin-vue-renderer-hocs'
import ElementRenderer from './element-renderer.vue'
import { useRenderers } from './renderer-vue-context'

const props = defineProps<VueRendererProps<DefaultController>>()
const { ElementRenderer: FinalElementRenderer = ElementRenderer } =
  useRenderers()
</script>

<template>
  <FinalElementRenderer
    v-for="child of props.__ctx__.children"
    v-bind="props.__ctx__.children.length === 1 ? $attrs : {}"
    :key="child.key"
    :__ctx__="child"
  />
</template>

// packages/runtime/react-runtime/src/plugins/runtime-plugin-react-renderer/controller-renderer.tsx
import type { DefaultController } from '@p-lc/runtime'
import type { FC } from 'react'
import { forwardRef } from 'react'
import type { ReactRendererProps } from '../runtime-plugin-react-renderer-hocs'
import { ElementRenderer } from './element-renderer'
import { useRenderers } from './renderer-react-context'

/**
 * 控制器渲染器
 */
export const ControllerRenderer: FC<ReactRendererProps<DefaultController>> =
  forwardRef(({ __ctx__: { children }, ...restProps }, ref) => {
    const { ElementRenderer: FinalElementRenderer = ElementRenderer } =
      useRenderers()
    const ps =
      children.length === 1
        ? {
            ...restProps,
            ref,
          }
        : {}
    return children.map((child) => (
      <FinalElementRenderer key={child.key} {...ps} __ctx__={child} />
    ))
  })
