// packages/runtime/vue-runtime/src/plugins/runtime-plugin-vue-renderer/element-renderer.vue
<script setup lang="ts">
import type { DefaultElement } from '@p-lc/runtime'
import { STR_CHILDREN } from '@p-lc/shared'
import { isFunction, keys, mapValues, omit, pick } from 'lodash-uni'
import { computed } from 'vue'
import { isVueSlot } from '../runtime-plugin-expression-slot-vue'
import type { VueRendererProps } from '../runtime-plugin-vue-renderer-hocs'
import ControllerRenderer from './controller-renderer.vue'
import { useRenderers } from './renderer-vue-context'

const props = defineProps<VueRendererProps<DefaultElement>>()
const slots = defineSlots<{ default?: unknown }>()
const component = computed(() => props.__ctx__.component)
const ctxProps = computed(() => props.__ctx__.props)
const hasPropChildren = computed(() => STR_CHILDREN in ctxProps.value)
const namedSlotKeys = computed(() => {
  return keys(ctxProps.value).filter(
    (key) => key === STR_CHILDREN || isVueSlot(ctxProps.value[key]),
  )
})
const finalSlots = computed(() => {
  let ret = pick(ctxProps.value, namedSlotKeys.value)
  if (hasPropChildren.value) {
    ret.default = ret.children
    delete ret.children
  }
  // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
  ret = mapValues(ret, (value) => (isFunction(value) ? value : () => value))
  ret = {
    ...ret,
    ...slots,
  }
  return ret
})
const ctxPropsOmitSlots = computed(() =>
  omit(ctxProps.value, namedSlotKeys.value),
)
const children = computed(() => props.__ctx__.children)
const { ControllerRenderer: FinalControllerRenderer = ControllerRenderer } =
  useRenderers()
</script>

<template>
  <component :is="component" v-bind="{ ...ctxPropsOmitSlots, ...$attrs }">
    <template v-if="!hasPropChildren">
      <FinalControllerRenderer
        v-for="child of children"
        :key="child.key"
        :__ctx__="child"
      />
    </template>
    <template v-for="(value, key) in finalSlots" #[key]>
      <component :is="value" />
    </template>
  </component>
</template>

// packages/runtime/react-runtime/src/plugins/runtime-plugin-react-renderer/element-renderer.tsx
import { supportRef } from '@p-lc/react-shared'
import type { DefaultElement } from '@p-lc/runtime'
import type { UnknownObject } from '@p-lc/shared'
import { STR_CHILDREN } from '@p-lc/shared'
import { isArray, isUndefined } from 'lodash-uni'
import type { FC } from 'react'
import { forwardRef } from 'react'
import type { ReactRendererProps } from '../runtime-plugin-react-renderer-hocs'
import { ControllerRenderer } from './controller-renderer'
import { useRenderers } from './renderer-react-context'

/**
 * 元素渲染器
 */
export const ElementRenderer: FC<ReactRendererProps<DefaultElement>> =
  forwardRef(
    ({ __ctx__: { component, props, children }, ...restProps }, ref) => {
      const {
        ControllerRenderer: FinalControllerRenderer = ControllerRenderer,
      } = useRenderers()
      let finalChildren
      if (STR_CHILDREN in restProps) {
        finalChildren = restProps.children
      } else {
        let ch =
          STR_CHILDREN in props
            ? props.children
            : children.map((child) => (
                <FinalControllerRenderer key={child.key} __ctx__={child} />
              ))
        if (isArray(ch) && ch.length <= 1) {
          // 减少 children 数组引用变化引起的渲染
          ch = ch[0]
        }
        finalChildren = ch
      }
      const finalProps = {
        ...props,
        ...restProps,
      }
      if (!isUndefined(finalChildren)) {
        finalProps.children = finalChildren
      }
      const C = component as FC<UnknownObject>
      return <C {...finalProps} ref={supportRef(C) ? ref : null} />
    },
  )
