// packages/runtime/react-runtime/src/plugins/runtime-plugin-react-renderer/runtime-renderer.tsx
import type { DefaultRuntime } from '@p-lc/runtime'
import type { FC } from 'react'
import { forwardRef } from 'react'
import type { ReactRendererProps } from '../runtime-plugin-react-renderer-hocs'
import { ControllerRenderer } from './controller-renderer'
import { useRenderers } from './renderer-react-context'

/**
 * 运行时渲染器
 */
export const RuntimeRenderer: FC<ReactRendererProps<DefaultRuntime>> =
  forwardRef(({ __ctx__: { view }, ...restProps }, ref) => {
    const { ControllerRenderer: FinalControllerRenderer = ControllerRenderer } =
      useRenderers()
    return (
      <FinalControllerRenderer
        key={view.key}
        {...restProps}
        ref={ref}
        __ctx__={view}
      />
    )
  })

// packages/runtime/vue-runtime/src/plugins/runtime-plugin-vue-renderer/runtime-renderer.vue
<script setup lang="ts">
import type { DefaultRuntime } from '@p-lc/runtime'
import type { VueRendererProps } from '../runtime-plugin-vue-renderer-hocs'
import ControllerRenderer from './controller-renderer.vue'
import { useRenderers } from './renderer-vue-context'

const props = defineProps<VueRendererProps<DefaultRuntime>>()
const { ControllerRenderer: FinalControllerRenderer = ControllerRenderer } =
  useRenderers()
</script>

<template>
  <FinalControllerRenderer
    :key="props.__ctx__.view.key"
    :__ctx__="props.__ctx__.view"
  />
</template>
